[package]
name = "loc"
version = "0.3.4"
description = "Count lines of code (cloc) fast."
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

repository = "https://github.com/cgag/loc"
homepage = "https://github.com/cgag/loc"
documentation = "https://github.com/cgag/loc"

license="MIT"

[dependencies]
clap          = "2.23.2"
deque         = "0.3.1"
itertools     = "0.5.10"
libc          = "0.2.21"
memchr        = "1.0.1"
memmap        = "0.5.2"
regex         = "0.2.1"
thread-scoped = "1.0.1"
num_cpus      = "1.3.0"
ignore        = "0.1.9"

# [profile.release]
# lto = true
