[package]
name = "loc"
version = "0.4.0"
description = "Count lines of code (cloc) fast."
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

repository = "https://github.com/cgag/loc"
homepage = "https://github.com/cgag/loc"
documentation = "https://github.com/cgag/loc"

license="MIT"

[dependencies]
clap          = "*"
deque         = "*"
itertools     = "*"
libc          = "*"
memchr        = "*"
memmap        = "*"
regex         = "*"
thread-scoped = "*"
num_cpus      = "*"
ignore        = "*"

# [profile.release]
# lto = true
