[package]
name = "count"
version = "0.1.0"
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

[dependencies]
ascii         = "*"
clap          = "*"
deque         = "*"
errno         = "*"
itertools     = "*"
libc          = "*"
memchr        = "*"
memmap        = "*"
mmap          = "*"
regex         = "*"
thread-scoped = "*"
walkdir       = "*"
num_cpus      = "*"


[profile.release]
lto = true
