[package]
name = "loc"
version = "0.3.4"
description = "Count lines of code (cloc) fast."
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

repository = "https://github.com/cgag/loc"
homepage = "https://github.com/cgag/loc"
documentation = "https://github.com/cgag/loc"

license="MIT"

[dependencies]
clap          = "2.20.0"
deque         = "0.3.1"
itertools     = "0.5.8"
libc          = "0.2.18"
memchr        = "1.0.1"
memmap        = "0.5.0"
regex         = "0.2.1"
thread-scoped = "1.0.1"
walkdir       = "1.0.7"
num_cpus      = "1.2.1"

[profile.release]
lto = true
