[package]
name = "loc"
version = "0.3.2"
description = "Count lines of code (cloc) fast."
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

repository = "https://github.com/cgag/loc"
homepage = "https://github.com/cgag/loc"
documentation = "https://github.com/cgag/loc"

license="Apache-2.0"

[dependencies]
ascii         = "0.7.1"
clap          = "2.14.0"
deque         = "0.3.1"
errno         = "0.1.8"
itertools     = "0.5.2"
libc          = "0.2.17"
memchr        = "0.1.11"
memmap        = "0.4.0"
mmap          = "0.1.1"
regex         = "0.1.77"
thread-scoped = "1.0.1"
walkdir       = "0.1.8"
num_cpus      = "1.1.0"

[profile.release]
lto = true
