[package]
name = "count"
version = "0.1.0"
authors = ["Curtis Gagliardi <curtis@curtis.io>"]

[dependencies]
thread-scoped = "*"
scoped_threadpool = "*"
memmap        = "*"
mmap          = "*"
libc          = "*"
errno         = "*"
memchr        = "*"
clap          = "*"
nom           = "*"
regex         = "*"
ascii         = "*"
walkdir       = "*"
itertools     = "*"
crossbeam     = "*"
